version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Node dependencies
  - package-ecosystem: "npm"
    directory: "/apps/web-dashboard"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
